-- Generated by Novel. Do not edit by hand.
-- Novel version: 0.2.7
local novel = require("novel")
local io = require("std/io")
local wl = require("std/wl_ui")
local time = require("std/time")

function main()
  io.println("Initializing Wayland client display connection...")
  local win = wl.createWindow("Novel Wayland Demo", 640, 480)
  if (win == nil) then
    io.println("Could not open Wayland display; check if WAYLAND_DISPLAY is active")
    return
  end
  io.println("Window mapped successfully; painting text...")
  wl.clear(win, 988970)
  wl.drawText(win, 40, 40, "Hello Wayland from Novel!", 16777215)
  wl.drawText(win, 40, 70, "Spawning native windows using FFI and C helper", 9741240)
  wl.drawText(win, 40, 100, "Drawing text using an embedded 8x8 font bitmap", 9741240)
  wl.drawText(win, 40, 150, "Cooperative loop yields execution via time.sleep", 9741240)
  wl.drawText(win, 40, 200, "Close the window or press Ctrl+C in terminal to exit", 16777215)
  wl.present(win)
  io.println("Entering Wayland event dispatch loop...")
  while true do
    local status = wl.dispatch(win)
    if (status < 0) then
      io.println("Window closed or display disconnected")
      break
    end
    time.sleep(0.016)
  end
  wl.close(win)
  io.println("Wayland display resources released; shutdown complete.")
end

novel.spawn(main)
novel.run()
