-- Novel bundle. Generated; do not edit by hand.
-- Bundled modules are registered before the entry runs.

package.preload["ui"] = function()
  -- Generated by Novel. Do not edit by hand.
  -- Novel version: 0.2.8
  local novel = require("novel")
  local ffi = require("std/ffi")
  local io = require("std/io")

  local WindowWrapper, init, getLib, createWindow, local_close_display, waitForKeypress
  WindowWrapper = {}
  WindowWrapper.__index = WindowWrapper

  function init()
    ffi.cdef("\n        typedef struct _XDisplay Display;\n        typedef unsigned long XID;\n        typedef XID Window;\n\n        typedef struct {\n            int type;\n            unsigned long serial;\n            int send_event;\n            Display *display;\n            Window window;\n        } XAnyEvent;\n\n        typedef union _XEvent {\n            int type;\n            XAnyEvent xany;\n            long pad[24];\n        } XEvent;\n\n        Display *XOpenDisplay(const char *display_name);\n        Window XDefaultRootWindow(Display *display);\n        Window XCreateSimpleWindow(Display *display, Window parent, int x, int y, unsigned int width, unsigned int height, unsigned int border_width, unsigned long border, unsigned long background);\n        int XSelectInput(Display *display, Window w, long event_mask);\n        int XMapWindow(Display *display, Window w);\n        int XNextEvent(Display *display, XEvent *event_return);\n        int XCloseDisplay(Display *display);\n    ")
  end

  function getLib()
    return ffi.load("X11")
  end

  function createWindow(title, width, height)
    init()
    local x11 = getLib()
    local XOpenDisplay = ffi.fn(x11, "XOpenDisplay")
    local XDefaultRootWindow = ffi.fn(x11, "XDefaultRootWindow")
    local XCreateSimpleWindow = ffi.fn(x11, "XCreateSimpleWindow")
    local XSelectInput = ffi.fn(x11, "XSelectInput")
    local XMapWindow = ffi.fn(x11, "XMapWindow")
    local display = XOpenDisplay(nil)
    if (display == nil) then
      io.println("Failed to open X display")
      return setmetatable({ display = nil, win = nil }, WindowWrapper)
    end
    local root = XDefaultRootWindow(display)
    local win = XCreateSimpleWindow(display, root, 100, 100, width, height, 1, 0, 988970)
    local eventMask = 32769
    XSelectInput(display, win, eventMask)
    XMapWindow(display, win)
    return setmetatable({ display = display, win = win }, WindowWrapper)
  end

  function local_close_display(display)
    local x11 = getLib()
    local XCloseDisplay = ffi.fn(x11, "XCloseDisplay")
    XCloseDisplay(display)
  end

  function waitForKeypress(w)
    local x11 = getLib()
    local XNextEvent = ffi.fn(x11, "XNextEvent")
    local event = ffi.new("XEvent")
    io.println("Window created successfully! Focus the window and press any key to exit.")
    while true do
      XNextEvent(w.display, event)
      if (event.type == 2) then
        io.println("Keypress detected, shutting down...")
        break
      end
    end
    local_close_display(w.display)
  end

  local __novel_exports = {}
  __novel_exports.WindowWrapper = WindowWrapper
  __novel_exports.createWindow = createWindow
  __novel_exports.waitForKeypress = waitForKeypress
  return __novel_exports

end

-- Generated by Novel. Do not edit by hand.
-- Novel version: 0.2.8
local novel = require("novel")
local io = require("std/io")
local ui = require("ui")

function main()
  io.println("Initializing simple UI window demo using X11 FFI...")
  local w = ui.createWindow("Novel Demo", 400, 300)
  if (w.display == nil) then
    io.println("Could not create window (X11 server not available or not running Linux)")
    return
  end
  ui.waitForKeypress(w)
  io.println("Window closed, demo finished.")
end

novel.spawn(main)
novel.run()
